{% set name = "rouge-score" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rouge_score-{{ version }}.tar.gz
  sha256: c7d4da2683e68c9abf0135ef915d63a46643666f848e558a1b9f7ead17ff0f04

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - absl-py
    - nltk
    - numpy
    - six >=1.14.0

test:
  imports:
    - rouge_score
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google-research/google-research/tree/master/rouge
  summary: Pure python implementation of ROUGE-1.5.5.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A naive python implementation of the original perl package, ROUGE from Google-Research.

    ## Overview

    This is a native python implementation of ROUGE, designed to replicate results from the original perl package.

    Maintainers may be contacted at [rouge-opensource@google.com](mailto:rouge-opensource@google.com).

    ROUGE was originally introduced in the paper:

    Lin, Chin-Yew. ROUGE: a Package for Automatic Evaluation of Summaries. In Proceedings of the Workshop on Text Summarization Branches Out (WAS 2004), Barcelona, Spain, July 25 - 26, 2004.

    ## ROUGE for Python

    There are ROUGE implementations available for Python, however some are not native python due to their dependency on the perl script, and others provide differing results when compared with the original implementation. This makes it difficult to directly compare with known results.

    This package is designed to replicate perl results. It implements:

    - ROUGE-N (N-gram) scoring
    - ROUGE-L (Longest Common Subsequence) scoring
    - Text normalization
    - Bootstrap resampling for confidence interval calculation
    - Optional Porter stemming to remove plurals and word suffixes such as (ing, ion, ment).

    Note that not all options provided by the original perl ROUGE script are supported, but the subset of options that are implemented should replicate the original functionality.

    PyPI: [https://pypi.org/project/rouge-score/](https://pypi.org/project/rouge-score/)

extra:
  recipe-maintainers:
    - sugatoray
